import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
import{makePlan,loadState,saveState,normalizeState}from'./lib/planner.js';
const menu=[['dashboard','الرئيسية'],['goals','الأهداف'],['tasks','المهام'],['roadmap','خارطة 30 يوم'],['study','الدراسة'],['skills','المهارات'],['money','المال'],['travel','إيطاليا والسفر'],['habits','العادات'],['notes','الملاحظات'],['planner','AI Life Planner'],['progress','التقدم']];
const labels={goals:'الأهداف',tasks:'المهام اليومية',study:'الدراسة',skills:'المهارات',money:'المال',travel:'إيطاليا والسفر',habits:'العادات',notes:'الملاحظات'};
const uid=()=>globalThis.crypto?.randomUUID?.()||String(Date.now()+Math.random());
function App(){const[s,setS]=useState(()=>normalizeState(loadState()));const[p,setP]=useState(()=>s.profile.onboarded?'dashboard':'landing');const[error,setError]=useState('');
function save(x){try{const n=normalizeState(x);setS(n);saveState(n);setError('')}catch{setError('تعذر حفظ البيانات محليًا. صدّر نسخة احتياطية ثم حاول مجددًا.')}}
function add(k,title){if(!title?.trim())return;save({...s,[k]:[...(s[k]||[]),{id:uid(),title:title.trim(),done:false,createdAt:new Date().toISOString()}]})}
function toggle(k,id){save({...s,[k]:(s[k]||[]).map(x=>x.id===id?{...x,done:!x.done}:x)})}
function remove(k,id){save({...s,[k]:(s[k]||[]).filter(x=>x.id!==id)})}
function exportData(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lifecraft-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{save(JSON.parse(r.result));setP('dashboard')}catch{setError('ملف النسخة الاحتياطية غير صالح.')}};r.readAsText(f)}
const plan=useMemo(()=>makePlan(s.profile),[s.profile]);
if(p==='landing')return <Landing onStart={()=>setP('onboarding')}/>;
if(p==='onboarding')return <Onboarding s={s} save={save} onDone={()=>{save({...s,profile:{...s.profile,onboarded:true}});setP('dashboard')}}/>;
const current=menu.find(x=>x[0]===p)?.[1]||'الرئيسية';
return <div className="app"><aside><div className="brand">LifeCraft <small>AI</small><span>نظام بناء الحياة</span></div><nav>{menu.map(x=><button key={x[0]} className={p===x[0]?'on':''} onClick={()=>setP(x[0])}>{x[1]}</button>)}</nav><div className="backup"><button onClick={exportData}>⬇ تصدير</button><label>⬆ استيراد<input type="file" accept="application/json" onChange={importData}/></label></div><footer>مجاني · بلا إعلانات · بلا اشتراك</footer></aside><main><header><span>LifeCraft AI</span><b>{current}</b></header>{error&&<div className="error">{error}</div>}{p==='dashboard'&&<Dashboard s={s} plan={plan} setP={setP}/>} {p==='planner'&&<Planner s={s} save={save} plan={plan}/>} {p==='roadmap'&&<Roadmap plan={plan}/>} {p==='progress'&&<Progress s={s}/>} {p==='goals'&&<Goals s={s} save={save}/>} {p==='study'&&<Study s={s} save={save}/>} {p==='money'&&<Money s={s} save={save}/>} {p==='travel'&&<Travel s={s} save={save}/>} {p==='habits'&&<Habits s={s} save={save}/>} {['tasks','skills','notes'].includes(p)&&<List s={s} add={add} toggle={toggle} remove={remove} k={p}/>} </main></div>}
function Landing({onStart}){return <main className="landing"><div className="landing-card"><span className="eyebrow">LIFECRAFT AI · FREE & OPEN</span><h1>ابنِ حياة تشبه أهدافك.</h1><p>مكان واحد لتنظيم أهدافك، دراستك، مهاراتك، مالك، عاداتك وخطط السفر، مع مخطط حياة ذكي يحول الفكرة إلى خطوات.</p><div className="landing-actions"><button onClick={onStart}>ابدأ بناء خطتك ✦</button><span>بياناتك محفوظة محليًا على جهازك</span></div><div className="feature-strip"><span>🎯 أهداف</span><span>📚 دراسة</span><span>💰 مال</span><span>✈️ سفر</span><span>🔥 عادات</span><span>🧠 AI Planner</span></div></div></main>}
function Onboarding({s,save,onDone}){return <main className="landing"><section className="onboarding panel"><span className="eyebrow">خطوتك الأولى</span><h1>خلينا نبني الخطة حول حياتك.</h1><p className="muted">هذه البيانات قابلة للتعديل لاحقًا.</p><label>ما الهدف الأكبر الآن؟<textarea value={s.profile.goal} onChange={e=>save({...s,profile:{...s.profile,goal:e.target.value}})} placeholder="مثال: دراسة القانون في إيطاليا"/></label><label>الساعات المتاحة يوميًا<input type="number" min="1" max="24" value={s.profile.hours} onChange={e=>save({...s,profile:{...s.profile,hours:e.target.value}})}/></label><label>الميزانية<input value={s.profile.budget} onChange={e=>save({...s,profile:{...s.profile,budget:e.target.value}})} placeholder="مثال: 200 دينار"/></label><label>الوجهة أو المسار<input value={s.profile.destination} onChange={e=>save({...s,profile:{...s.profile,destination:e.target.value}})}/></label><label>الأولويات<input value={s.profile.priorities} onChange={e=>save({...s,profile:{...s.profile,priorities:e.target.value}})}/></label><button className="primary" onClick={onDone}>ابدأ LifeCraft AI 🚀</button></section></main>}
function Dashboard({s,plan,setP}){const completed=s.tasks.filter(x=>x.done).length;return <><section className="hero"><span className="eyebrow">خطة اليوم</span><h1>ابنِ حياة تشبه أهدافك.</h1><p>حوّل أهدافك الكبيرة إلى خطوات صغيرة قابلة للتنفيذ.</p><button onClick={()=>setP('planner')}>✦ افتح AI Life Planner</button></section><div className="cards"><Card a="الأهداف" b={s.goals.length}/><Card a="المهام" b={s.tasks.length}/><Card a="المكتمل اليوم" b={completed}/><Card a="العادات" b={s.habits.length}/></div><section className="panel"><div className="section-title"><h3>أهم 3 أفعال اليوم</h3><span>ركّز على التنفيذ</span></div>{plan.today.map((x,i)=><p key={i} className="task">□ {x}</p>)}<h3>الخطوة التالية</h3><div className="next">{plan.next}</div></section></>}
function Card({a,b}){return <div className="card"><small>{a}</small><strong>{b}</strong></div>}
function Planner({s,save,plan}){return <div className="grid"><section className="panel"><div className="section-title"><h3>AI Life Planner</h3><span>الخطة تتحدث تلقائيًا</span></div><label>الهدف<textarea value={s.profile.goal} onChange={e=>save({...s,profile:{...s.profile,goal:e.target.value}})}/></label><label>الساعات اليومية<input type="number" min="1" max="24" value={s.profile.hours} onChange={e=>save({...s,profile:{...s.profile,hours:e.target.value}})}/></label><label>الميزانية<input value={s.profile.budget} onChange={e=>save({...s,profile:{...s.profile,budget:e.target.value}})}/></label><label>الوجهة<input value={s.profile.destination} onChange={e=>save({...s,profile:{...s.profile,destination:e.target.value}})}/></label><label>الأولويات<input value={s.profile.priorities} onChange={e=>save({...s,profile:{...s.profile,priorities:e.target.value}})}/></label></section><section className="panel"><h3>{plan.title}</h3><h4>المراحل</h4>{plan.milestones.map((x,i)=><p key={i} className="line">✓ {x}</p>)}<h4>أهم 3 أفعال</h4>{plan.today.map((x,i)=><p key={i} className="line">→ {x}</p>)}<h4>العوائق المحتملة</h4>{plan.blockers.map((x,i)=><p key={i} className="warn">⚠ {x}</p>)}<h4>التالي</h4><div className="next">{plan.next}</div></section></div>}
function Roadmap({plan}){return <section className="panel"><div className="section-title"><h3>خارطة 30 يومًا</h3><span>4 مراحل تنفيذية</span></div>{plan.roadmap.map((w,i)=><article className="week" key={i}><small>الأسبوع {i+1}</small><b>{w.focus}</b><p>{w.tasks.join(' · ')}</p></article>)}</section>}
function Progress({s}){const all=Object.entries(labels).flatMap(([k])=>s[k]);const done=all.filter(x=>x.done).length;const pct=all.length?Math.round(done/all.length*100):0;return <><section className="cards"><Card a="إجمالي العناصر" b={all.length}/><Card a="مكتمل" b={done}/><Card a="نسبة الإنجاز" b={pct+'%'}/><Card a="الأهداف" b={s.goals.length}/></section><section className="panel"><h3>نبض التقدم</h3><div className="progress"><span style={{width:pct+'%'}}/></div><p className="muted">أنجز خطوة واحدة اليوم. الاستمرارية أهم من محاولة تغيير كل شيء دفعة واحدة.</p></section></>}
function Goals({s,save}){const[v,setV]=useState('');const add=()=>{if(!v.trim())return;save({...s,goals:[...s.goals,{id:uid(),title:v.trim(),done:false,progress:0}]});setV('')};const update=(id,progress)=>save({...s,goals:s.goals.map(x=>x.id===id?{...x,progress:Number(progress),done:Number(progress)>=100}:x)});return <section className="panel"><div className="section-title"><h3>🎯 أهدافي</h3><span>{s.goals.filter(x=>x.done).length}/{s.goals.length} مكتمل</span></div><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="مثال: إنهاء التوجيهي بنسبة 90%"/><button onClick={add}>＋ هدف</button></div>{s.goals.map(x=><div className="goal-card" key={x.id}><div className="section-title"><b>{x.title}</b><span>{x.progress||0}%</span></div><input type="range" min="0" max="100" value={x.progress||0} onChange={e=>update(x.id,e.target.value)}/><div className="progress"><span style={{width:(x.progress||0)+'%'}}/></div></div>)}</section>}
function Study({s,save}){const[v,setV]=useState('');const[h,setH]=useState(1);const add=()=>{if(!v.trim())return;save({...s,study:[...s.study,{id:uid(),title:v.trim(),hours:Number(h),done:false}]});setV('')};return <section className="panel"><div className="section-title"><h3>📚 مخطط الدراسة</h3><span>{s.study.reduce((a,x)=>a+(x.hours||0),0)} ساعة مخططة</span></div><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} placeholder="المادة أو الجلسة"/><input className="small-input" type="number" min="0.5" step="0.5" value={h} onChange={e=>setH(e.target.value)}/><button onClick={add}>＋ إضافة</button></div>{s.study.map(x=><div className={'item '+(x.done?'done':'')} key={x.id}><button className="check" onClick={()=>save({...s,study:s.study.map(y=>y.id===x.id?{...y,done:!y.done}:y)})}>{x.done?'✓':'○'}</button><span>{x.title} · {x.hours} ساعة</span></div>)}</section>}
function Money({s,save}){const[v,setV]=useState('');const[a,setA]=useState('');const add=()=>{if(!v.trim()||!a)return;save({...s,money:[...s.money,{id:uid(),title:v.trim(),amount:Number(a),done:false}]});setV('');setA('')};const total=s.money.reduce((x,y)=>x+(Number(y.amount)||0),0);return <section className="panel"><div className="section-title"><h3>💰 أهداف المال</h3><span>المجموع {total.toLocaleString()} </span></div><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} placeholder="مثال: رأس مال مشروع"/><input type="number" value={a} onChange={e=>setA(e.target.value)} placeholder="المبلغ"/><button onClick={add}>＋ إضافة</button></div>{s.money.map(x=><div className="item" key={x.id}><span>{x.title}</span><b>{Number(x.amount).toLocaleString()}</b></div>)}</section>}
function Travel({s,save}){const[v,setV]=useState('');const add=()=>{if(!v.trim())return;save({...s,travel:[...s.travel,{id:uid(),title:v.trim(),done:false}]});setV('')};const defaults=['اختيار الجامعة والمدينة','حساب تكاليف السكن والمعيشة','تجهيز الوثائق المطلوبة','تطوير اللغة الإيطالية','تحديد ميزانية السفر'];return <section className="panel"><div className="section-title"><h3>🇮🇹 إيطاليا والسفر</h3><span>قائمة الاستعداد</span></div><button onClick={()=>defaults.forEach((x,i)=>{if(!s.travel.some(y=>y.title===x))s.travel.push({id:uid(),title:x,done:false})});save({...s})}>＋ إنشاء قائمة إيطاليا</button><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} placeholder="أضف خطوة سفر..."/><button onClick={add}>إضافة</button></div>{s.travel.map(x=><div className={'item '+(x.done?'done':'')} key={x.id}><button className="check" onClick={()=>save({...s,travel:s.travel.map(y=>y.id===x.id?{...y,done:!y.done}:y)})}>{x.done?'✓':'○'}</button><span>{x.title}</span></div>)}</section>}
function Habits({s,save}){const[v,setV]=useState('');const add=()=>{if(!v.trim())return;save({...s,habits:[...s.habits,{id:uid(),title:v.trim(),done:false,streak:0}]});setV('')};return <section className="panel"><div className="section-title"><h3>🔥 العادات</h3><span>ابنِ سلسلة يومية</span></div><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} placeholder="مثال: صلاة الفجر / 30 دقيقة دراسة"/><button onClick={add}>＋ عادة</button></div>{s.habits.map(x=><div className={'item '+(x.done?'done':'')} key={x.id}><button className="check" onClick={()=>save({...s,habits:s.habits.map(y=>y.id===x.id?{...y,done:!y.done,streak:(y.done?Math.max(0,(y.streak||1)-1):(y.streak||0)+1)}:y)})}>{x.done?'✓':'○'}</button><span>{x.title}</span><small>🔥 {x.streak||0} يوم</small></div>)}</section>}
function List({s,add,toggle,remove,k}){const[v,setV]=useState('');return <section className="panel"><div className="section-title"><h3>{labels[k]}</h3><span>{(s[k]||[]).filter(x=>x.done).length}/{(s[k]||[]).length} مكتمل</span></div><div className="add-row"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){add(k,v);setV('')}}} placeholder="اكتب عنصرًا جديدًا..."/><button onClick={()=>{add(k,v);setV('')}}>＋ إضافة</button></div>{(s[k]||[]).length===0?<p className="muted">لا يوجد شيء بعد. أضف أول عنصر وابدأ.</p>:(s[k]||[]).map(x=><div className={'item '+(x.done?'done':'')} key={x.id||x.title}><button className="check" onClick={()=>toggle(k,x.id)}>{x.done?'✓':'○'}</button><span>{x.title||x.text}</span><button className="delete" onClick={()=>remove(k,x.id)} aria-label="حذف">×</button></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);